export const lang = {
  en: {
    title: "Sign Out",
    headingLoginForm: "Sign in to your Account",
    authHeadingSignUp: "Sign up to your account",
    email: "Email address",
    password: "Password",
    signInButtonLabel: "Sign in",
    footerText: "Not a member?",
    signUp: "Sign up",
    fullName: "Full Name",
    alreadyMember: "Already a member?",
    signOut: "Sign Out",
    gptSearch: "GPT Search",
  },

  hi: {
    title: "साइन आउट",
    headingLoginForm: "अपने खाते में साइन इन करें",
    authHeadingSignUp: "अपना खाता बनाएं",
    email: "ईमेल पता",
    password: "पासवर्ड",
    signInButtonLabel: "साइन इन करें",
    footerText: "सदस्य नहीं हैं?",
    signUp: "साइन अप करें",
    fullName: "पूरा नाम",
    alreadyMember: "क्या आप पहले से सदस्य हैं?",
    signOut: "साइन आउट",
    gptSearch: "GPT खोज",
  },

  fr: {
    title: "Se déconnecter",
    headingLoginForm: "Connectez-vous à votre compte",
    authHeadingSignUp: "Créez votre compte",
    email: "Adresse e-mail",
    password: "Mot de passe",
    signInButtonLabel: "Se connecter",
    footerText: "Pas encore membre ?",
    signUp: "S'inscrire",
    fullName: "Nom complet",
    alreadyMember: "Déjà membre ?",
    signOut: "Se déconnecter",
    gptSearch: "Recherche GPT",
  },
};
